// context/SettingsContext.js
import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useContext, useEffect, useState } from "react";

const SettingsContext = createContext({});
export const useSettings = () => useContext(SettingsContext);

const TRANSLATIONS = {
  en: {
    // NAV
    home: "Home", evacuate: "Evacuate", hotlines: "Hotlines",
    weather: "Weather", profile: "Profile",
    admin: "Admin", first_aid: "First Aid", checklist: "Checklist",
    drrm: "DRRM", voice: "Voice", settings: "Settings",
    // HOME
    good_morning: "Good Morning", good_afternoon: "Good Afternoon",
    good_evening: "Good Evening",
    quick_access: "Quick Access", all_features: "All features",
    disaster_tips: "Disaster Tips", tap_to_expand: "Tap to expand",
    marked_safe: "Marked Safe",
    status_unknown: "Status Unknown", mark_safe: "MARK\nSAFE",
    safe: "SAFE", your_status: "YOUR STATUS", student: "Student",
    ctu_drrmo_system: "CTU Danao Campus - DRRMO System",
    emergency_quick_access: "Emergency Quick Access",
    immediate_help: "Immediate assistance and rescue options",
    call_911: "Call 911",
    emergency_active: "EMERGENCY ACTIVE", emergency_alert: "Emergency Alert",
    view_evacuation_centers: "View Evacuation Centers",
    drrmo_announcement: "DRRMO ANNOUNCEMENT",
    stay_prepared: "Stay Prepared", always_ready: "Always ready",
    tap_to_collapse: "Tap to collapse", tap_for_quick_tip: "Tap for quick tip",
    flood: "Flood", earthquake: "Earthquake", typhoon: "Typhoon", fire: "Fire",
    flood_tip: "Move to higher ground immediately. Avoid walking in moving water. Never drive through flooded roads.",
    earthquake_tip: "Drop, Cover, and Hold On. Stay away from windows and heavy furniture.",
    typhoon_tip: "Stay indoors. Keep away from windows and doors. Unplug electrical appliances.",
    fire_tip: "Use evacuation routes. Stay low to avoid smoke. Never use elevators.",
    go_bag: "Go Bag", family_plan: "Family Plan", know_routes: "Know Routes",
    go_bag_desc: "3-day supplies: food, water, meds, documents.",
    family_plan_desc: "Have a meeting point and contact list ready.",
    first_aid_desc: "Know basic first aid and CPR procedures.",
    know_routes_desc: "Know your nearest evacuation center.",
    online: "Online", offline: "Offline",
    // EVACUATION
    evacuation_title: "Evacuation Centers",
    evacuation_sub: "Danao City Safe Zones & Evacuation Guide",
    evacuation_alert: "EVACUATION ALERT", emergency_mode_active: "EMERGENCY MODE ACTIVE",
    state_emergency: "STATE OF EMERGENCY", evacuate_now: "State of Emergency - Evacuate Now!",
    proceed_nearest: "Proceed IMMEDIATELY to the nearest evacuation center below",
    nearest: "NEAREST", go_here_now: "GO HERE NOW",
    start_navigation: "START NAVIGATION", persons: "persons",
    primary: "Primary", secondary: "Secondary", away: "away",
    calculating_safe_zone: "Calculating nearest safe zone...",
    location_unavailable: "Location Unavailable", allow_location: "Allow location access for accurate results",
    view_all_maps: "View All on Google Maps", see_all_safe_zones: "See all safe zones near Danao City",
    go: "GO", avoid_areas: "Avoid These Areas", stay_away_zones: "Stay away from these zones during emergencies",
    danger_note: "Danger zones are identified by local DRRMO. Always follow official evacuation orders and avoid these areas during disasters.",
    evacuation_tips: "Evacuation Tips", follow_emergencies: "Follow these during emergencies",
    safe_zones: "Safe Zones", danger_zones: "Danger Zones",
    monitoring: "Monitoring", centers: "Centers",
    danger: "Danger Zones", tips: "Tips",
    ctu_drrmo_hotline: "CTU Danao DRRMO Hotline",
    // FIRST AID
    firstaid_title: "First Aid Guide",
    firstaid_sub: "Step-by-step emergency instructions",
    guides: "Guides", emergency: "Emergency", offline_label: "Free",
    all: "All", critical: "Critical",
    injury: "Injury", disaster: "Disaster",
    // FAMILY
    family_title: "Family & Peers",
    family_sub: "Stay connected during emergencies",
    contacts: "Contacts", requests: "Requests", find: "Find",
    i_am_safe: "I Am Safe", need_help: "Need Help",
    // SETTINGS
    settings_title: "Settings", language_label: "Language",
    app_language_en: "App is in English",
    app_language_ceb: "The app is in Cebuano",
    app_language_fil: "The app is in Tagalog",
    appearance: "Appearance", dark_mode: "Dark Mode",
    dark_theme_enabled: "Dark theme enabled", light_theme_enabled: "Light theme enabled",
    notifications_label: "Notifications", emergency_alerts: "Emergency Alerts",
    receiving_alerts: "Receiving real-time alerts", alerts_disabled: "Alerts disabled",
    voice_speed: "Voice Guide Speed", account: "Account",
    slow: "Slow", normal: "Normal", fast: "Fast",
    edit_name: "Edit Display Name", change_password: "Change Password",
    update_name_desc: "Update your name in the app",
    update_password_desc: "Update your account password",
    information: "Information", about: "About LIFELINE",
    privacy: "Privacy Policy", logout: "Logout",
    version_info: "Version info and credits", data_handling: "How we handle your data",
    active: "Active", close: "Close", display_name: "Display name",
    current_password: "Current password", new_password: "New password",
    confirm_new_password: "Confirm new password", saving: "Saving...",
    // PROFILE
    profile_title: "My Profile",
    profile_sub: "Manage your personal information",
    personal_info: "Personal Information", emergency_contact: "Emergency Contact",
    edit_profile: "Edit Profile", save_changes: "Save Changes",
    cancel: "Cancel", saved: "Saved!", profile_updated: "Your profile has been updated.",
    full_name: "Full Name", email: "Email", phone_number: "Phone Number",
    barangay_address: "Barangay / Address", contact_name: "Contact Name",
    contact_number: "Contact Number", current_location: "Current Location",
    address_privacy: "Address Privacy", address_public: "Address is Public",
    address_private: "Address is Private", contacts_can_see_address: "Your contacts can see your address",
    only_you_address: "Only you can see your address", your_name: "Your Name",
    enter_name: "Enter your name", enter_phone: "Enter phone number",
    enter_address: "Enter your address",
    // WEATHER
    windy_map: "Windy Map", unknown: "Unknown",
    permission_denied: "Permission Denied", location_required: "Location access is required.",
    could_not_fetch_weather: "Could not fetch weather. Check your internet connection.",
    try_again: "Try Again", no_weather_data: "No weather data available.",
    notification_sent: "Notification sent to your device", feels_like: "Feels like",
    humidity: "Humidity", wind: "Wind", visibility: "Visibility", pressure: "Pressure",
    next_24_hours: "Next 24 Hours", sun_schedule: "Sun Schedule",
    sunrise: "Sunrise", sunset: "Sunset", earthquake_monitor: "Earthquake Monitor",
    usgs_detection: "USGS Real-Time Detection",
    quake_desc: "LIFELINE automatically monitors USGS earthquake data every 15 minutes. If a Magnitude 4.0+ earthquake is detected near Danao City, all users will be alerted automatically with a buzzer notification.",
    check_now: "Check Now", official_updates: "Official Updates",
    refresh_weather: "Refresh Weather",
    windy_info: "Live wind, rain, and typhoon map powered by Windy",
    loading_windy: "Loading Windy Map...",
    quake_detected: "Earthquake Detected!",
    quake_detected_msg: "A significant earthquake has been detected near Danao City. Emergency alert has been activated for ALL users automatically.",
    no_quake_detected: "No Earthquake Detected",
    no_quake_msg: "No significant earthquakes (Magnitude 4.0+) detected near Danao City in the last 24 hours.",
    check_quake_error: "Could not check earthquake data. Check your internet connection.",
    // VOICE
    voice_guide: "Voice Guide", voice_sub: "Audio evacuation instructions",
    select_language: "Select Language:", how_to_use: "How to use",
    voice_how_desc: "Select a disaster type below, then tap Start Voice Guide to hear step-by-step evacuation instructions. Tap any step to replay it.",
    choose_disaster: "Choose Disaster Type", voice_detail_sub: "Voice-Guided Evacuation Instructions",
    start_voice: "Start Voice Guide", stop: "Stop", steps_tap: "steps - Tap to start voice guide",
    // HOTLINES
    emergency_hotlines: "Emergency Hotlines", tap_number_call: "Tap any number to call directly",
    call: "Call",
    my_status: "My Status", no_pending_requests: "No pending requests",
    search_add_people: "Search for family or peers to add them.",
    contact_requests_here: "Contact requests will appear here.",
    no_users_found: "No users found", lifeline_user: "LIFELINE User",
    added: "Added", add: "+ Add", message_placeholder: "Type a message...",
    preparedness_checklists: "Preparedness Checklists",
    checklist_sub: "Track your disaster readiness - progress saves automatically",
    reset_checklist: "Reset Checklist", completed: "completed",
    items_completed: "items completed", checklist_complete: "Checklist Complete!",
    checklist_complete_sub: "Great job! You are well prepared.",
    overall_preparedness: "Overall Preparedness", ready: "Ready",
    total_items_completed: "total items completed",
    disaster_guides: "Disaster Guides", offline_mode: "Offline Mode Active",
    before: "Before", during: "During", after: "After", step: "Step",
    firstaid_emergency_procedure: "EMERGENCY PROCEDURE", steps: "Steps",
    done: "Done", progress: "Progress", emergency_hotline: "Emergency Hotline",
    drrm_safe_zones: "DRRM & Safe Zones",
    drrm_sub: "CTU Danao Campus Safety Information",
    drrm_awareness: "DRRM Awareness", view_ctu_maps: "View CTU Danao on Google Maps",
    see_campus_layout: "See campus layout and safe zones",
    ctu_safe_zones: "CTU Danao Safe Zones", hazard_zones: "Hazard Zones",
    topics_tap: "topics - Tap to read",
    // GENERAL
    back: "Back", search: "Search by name...",
    no_contacts: "No contacts yet", find_people: "Find People",
    call_now: "Tap to call", tap_navigate: "Tap to open in Google Maps",
  },
  ceb: {
    // NAV
    home: "Panimalay", evacuate: "Likas", hotlines: "Hotlines",
    weather: "Panahon", profile: "Profile",
    admin: "Admin", first_aid: "Unang Bulig", checklist: "Checklist",
    drrm: "DRRM", voice: "Tingog", settings: "Settings",
    // HOME
    good_morning: "Maayong Buntag", good_afternoon: "Maayong Hapon",
    good_evening: "Maayong Gabii",
    quick_access: "Dali nga Access", all_features: "Tanan nga features",
    disaster_tips: "Mga Tip sa Kalamidad", tap_to_expand: "I-tap para mabukas",
    marked_safe: "Luwas na",
    status_unknown: "Wala'y Kahimtang", mark_safe: "MARKAHI\nLUWAS",
    safe: "LUWAS", your_status: "IMONG KAHIMTANG", student: "Estudyante",
    ctu_drrmo_system: "CTU Danao Campus - DRRMO System",
    emergency_quick_access: "Dali nga Emergency Access",
    immediate_help: "Direktang tabang ug rescue options",
    call_911: "Tawag 911",
    emergency_active: "AKTIBO NGA EMERHENSYA", emergency_alert: "Alerto sa Emerhensya",
    view_evacuation_centers: "Tan-awa ang Evacuation Centers",
    drrmo_announcement: "PAHIBALO SA DRRMO",
    stay_prepared: "Pag-andam Kanunay", always_ready: "Kanunay andam",
    tap_to_collapse: "I-tap para sirad-an", tap_for_quick_tip: "I-tap para sa dali nga tip",
    flood: "Baha", earthquake: "Linog", typhoon: "Bagyo", fire: "Sunog",
    flood_tip: "Adto dayon sa mas taas nga lugar. Likayi ang paglakaw sa kusog nga tubig. Ayaw pagdrayb sa baha nga dalan.",
    earthquake_tip: "Duko, Tabon, ug Gunit. Palayo sa bintana ug bug-at nga muwebles.",
    typhoon_tip: "Pabilin sa sulod. Palayo sa bintana ug pultahan. I-unplug ang electrical appliances.",
    fire_tip: "Gamita ang evacuation routes. Magpabilin sa ubos aron malikayan ang aso. Ayaw gamita ang elevator.",
    go_bag: "Go Bag", family_plan: "Plano sa Pamilya", know_routes: "Hibaloa ang Ruta",
    go_bag_desc: "3 ka adlaw nga suplay: pagkaon, tubig, tambal, dokumento.",
    family_plan_desc: "Pag-andam og meeting point ug listahan sa kontak.",
    first_aid_desc: "Hibaloa ang basic first aid ug CPR.",
    know_routes_desc: "Hibaloa ang pinakaduol nga evacuation center.",
    online: "Online", offline: "Offline",
    // EVACUATION
    evacuation_title: "Mga Sentro sa Evacuation",
    evacuation_sub: "Mga Luwas nga Lugar sa Danao City",
    evacuation_alert: "ALERTO SA EVACUATION", emergency_mode_active: "AKTIBO ANG EMERGENCY MODE",
    state_emergency: "KAHIMTANG SA EMERHENSYA", evacuate_now: "Kahimtang sa Emerhensya - Likas Karon!",
    proceed_nearest: "Adto DAYON sa pinakaduol nga evacuation center sa ubos",
    nearest: "PINAKALAPIT", go_here_now: "ADTO DINHI KARON",
    start_navigation: "SUGDI ANG NAVIGATION", persons: "ka tawo",
    primary: "Primary", secondary: "Secondary", away: "layo",
    calculating_safe_zone: "Gikalkula ang pinakaduol nga luwas nga lugar...",
    location_unavailable: "Dili Makita ang Lokasyon", allow_location: "Tugoti ang lokasyon para tukma ang resulta",
    view_all_maps: "Tan-awa Tanan sa Google Maps", see_all_safe_zones: "Tan-awa ang tanang luwas nga lugar duol sa Danao City",
    go: "ADTO", avoid_areas: "Likayi Kini nga mga Lugar", stay_away_zones: "Palayo niini nga mga zone panahon sa emerhensya",
    danger_note: "Ang delikadong mga lugar giila sa lokal nga DRRMO. Sunda kanunay ang opisyal nga evacuation orders ug likayi kini nga mga lugar panahon sa kalamidad.",
    evacuation_tips: "Mga Tip sa Evacuation", follow_emergencies: "Sunda kini panahon sa emerhensya",
    safe_zones: "Luwas nga Lugar", danger_zones: "Delikadong Lugar",
    monitoring: "Pagmonitor", centers: "Mga Sentro",
    danger: "Delikado", tips: "Mga Tip",
    ctu_drrmo_hotline: "CTU Danao DRRMO Hotline",
    // FIRST AID
    firstaid_title: "Unang Bulig",
    firstaid_sub: "Mga instruksyon sa emerhensya",
    guides: "Mga Gabay", emergency: "Emerhensya", offline_label: "Libre",
    all: "Tanan", critical: "Kritikal",
    injury: "Samad", disaster: "Kalamidad",
    // FAMILY
    family_title: "Pamilya ug Mga Kaedad",
    family_sub: "Magkonekta sa panahon sa emerhensya",
    contacts: "Mga Kontak", requests: "Mga Hangyo", find: "Pangita",
    i_am_safe: "Luwas Ko", need_help: "Nagkinahanglan Ko og Tabang",
    // SETTINGS
    settings_title: "Mga Setting", language_label: "Pinulongan",
    app_language_en: "Ang app kay English",
    app_language_ceb: "Ang app kay Cebuano",
    app_language_fil: "Ang app kay Tagalog",
    appearance: "Hitsura", dark_mode: "Dark Mode",
    dark_theme_enabled: "Aktibo ang dark theme", light_theme_enabled: "Aktibo ang light theme",
    notifications_label: "Mga Abiso", emergency_alerts: "Mga Alerto sa Emerhensya",
    receiving_alerts: "Nakadawat og real-time alerts", alerts_disabled: "Gi-disable ang alerts",
    voice_speed: "Tulin sa Tingog", account: "Account",
    slow: "Hinay", normal: "Normal", fast: "Paspas",
    edit_name: "I-edit ang Ngalan", change_password: "Usba ang Password",
    update_name_desc: "I-update ang imong ngalan sa app",
    update_password_desc: "I-update ang password sa imong account",
    information: "Impormasyon", about: "Mahitungod sa LIFELINE",
    privacy: "Polisiya sa Privacy", logout: "Logout",
    version_info: "Impormasyon sa bersyon ug credits", data_handling: "Giunsa namo pagdumala ang imong data",
    active: "Aktibo", close: "Sirado", display_name: "Display name",
    current_password: "Karon nga password", new_password: "Bag-ong password",
    confirm_new_password: "Kumpirmaha ang bag-ong password", saving: "Nag-save...",
    // PROFILE
    profile_title: "Akong Profile",
    profile_sub: "Pagdumala sa imong impormasyon",
    personal_info: "Personal nga Impormasyon", emergency_contact: "Kontak sa Emerhensya",
    edit_profile: "I-edit ang Profile", save_changes: "I-save ang Pagbag-o",
    cancel: "Kanselahon",
    saved: "Na-save!", profile_updated: "Na-update na ang imong profile.",
    full_name: "Tibuok Ngalan", email: "Email", phone_number: "Numero sa Telepono",
    barangay_address: "Barangay / Address", contact_name: "Ngalan sa Kontak",
    contact_number: "Numero sa Kontak", current_location: "Karon nga Lokasyon",
    address_privacy: "Privacy sa Address", address_public: "Public ang Address",
    address_private: "Private ang Address", contacts_can_see_address: "Makita sa imong contacts ang imong address",
    only_you_address: "Ikaw ra ang makakita sa imong address", your_name: "Imong Ngalan",
    enter_name: "Isulod ang imong ngalan", enter_phone: "Isulod ang numero sa telepono",
    enter_address: "Isulod ang imong address",
    windy_map: "Windy Map", unknown: "Wala Mailhi",
    permission_denied: "Wala Gitugotan", location_required: "Kinahanglan ang access sa lokasyon.",
    could_not_fetch_weather: "Dili makuha ang panahon. Susiha ang imong internet connection.",
    try_again: "Sulayi Pag-usab", no_weather_data: "Walay weather data.",
    notification_sent: "Gipadala ang abiso sa imong device", feels_like: "Murag",
    humidity: "Humidity", wind: "Hangin", visibility: "Visibility", pressure: "Pressure",
    next_24_hours: "Sunod 24 Oras", sun_schedule: "Iskedyul sa Adlaw",
    sunrise: "Pagsubang", sunset: "Pagsalop", earthquake_monitor: "Monitor sa Linog",
    usgs_detection: "USGS Real-Time Detection",
    quake_desc: "Ang LIFELINE awtomatikong nagmonitor sa USGS earthquake data matag 15 minutos. Kung makakita og Magnitude 4.0+ nga linog duol sa Danao City, tanan users alertohan dayon.",
    check_now: "Susiha Karon", official_updates: "Opisyal nga Updates",
    refresh_weather: "I-refresh ang Panahon",
    windy_info: "Live wind, rain, ug typhoon map powered by Windy",
    loading_windy: "Nag-load sa Windy Map...",
    quake_detected: "Nakit-an ang Linog!",
    quake_detected_msg: "Adunay dakong linog nga nakita duol sa Danao City. Ang emergency alert gi-activate para sa TANAN users.",
    no_quake_detected: "Walay Linog nga Nakit-an",
    no_quake_msg: "Walay dakong linog (Magnitude 4.0+) nga nakita duol sa Danao City sulod sa miaging 24 oras.",
    check_quake_error: "Dili masusi ang earthquake data. Susiha ang imong internet connection.",
    voice_guide: "Giya sa Tingog", voice_sub: "Audio nga instruksyon sa paglikas",
    select_language: "Pili og Pinulongan:", how_to_use: "Unsaon paggamit",
    voice_how_desc: "Pili og klase sa kalamidad sa ubos, dayon i-tap ang Start Voice Guide aron madungog ang lakang-lakang nga instruksyon. I-tap ang bisan unsang lakang aron paminawon usab.",
    choose_disaster: "Pili og Klase sa Kalamidad", voice_detail_sub: "Voice-Guided nga Instruksyon sa Evacuation",
    start_voice: "Sugdi ang Voice Guide", stop: "Hunong", steps_tap: "lakang - I-tap para magsugod ang voice guide",
    emergency_hotlines: "Emergency Hotlines", tap_number_call: "I-tap ang numero para motawag dayon",
    call: "Tawag",
    my_status: "Akong Kahimtang", no_pending_requests: "Walay pending nga hangyo",
    search_add_people: "Pangitaa ang pamilya o kauban para idugang sila.",
    contact_requests_here: "Ang contact requests makita dinhi.",
    no_users_found: "Walay users nga nakita", lifeline_user: "LIFELINE User",
    added: "Na-add", add: "+ Add", message_placeholder: "Isulat ang mensahe...",
    preparedness_checklists: "Mga Checklist sa Pagpangandam",
    checklist_sub: "I-track ang imong pagkaandam - awtomatikong ma-save ang progress",
    reset_checklist: "I-reset ang Checklist", completed: "nahuman",
    items_completed: "items nahuman", checklist_complete: "Kompleto ang Checklist!",
    checklist_complete_sub: "Maayo kaayo! Andam ka na.",
    overall_preparedness: "Kinatibuk-ang Pagkaandam", ready: "Andam",
    total_items_completed: "total items nahuman",
    disaster_guides: "Mga Giya sa Kalamidad", offline_mode: "Aktibo ang Offline Mode",
    before: "Sa Wala Pa", during: "Panahon", after: "Pagkahuman", step: "Lakang",
    firstaid_emergency_procedure: "PROSESO SA EMERHENSYA", steps: "Mga Lakang",
    done: "Nahuman", progress: "Progress", emergency_hotline: "Emergency Hotline",
    drrm_safe_zones: "DRRM ug Luwas nga Lugar",
    drrm_sub: "Impormasyon sa Kaluwasan sa CTU Danao Campus",
    drrm_awareness: "Kahibalo sa DRRM", view_ctu_maps: "Tan-awa ang CTU Danao sa Google Maps",
    see_campus_layout: "Tan-awa ang campus layout ug luwas nga lugar",
    ctu_safe_zones: "CTU Danao Luwas nga Lugar", hazard_zones: "Hazard Zones",
    topics_tap: "topics - I-tap para basahon",
    // GENERAL
    back: "Balik", search: "Pangita pinaagi sa ngalan...",
    no_contacts: "Wala pay mga kontak", find_people: "Pangita og Tawo",
    call_now: "I-tap para tawagan", tap_navigate: "I-tap para buksan sa Google Maps",
  },
  fil: {
    // NAV
    home: "Tahanan", evacuate: "Lumikas", hotlines: "Hotlines",
    weather: "Panahon", profile: "Profile",
    admin: "Admin", first_aid: "Unang Lunas", checklist: "Checklist",
    drrm: "DRRM", voice: "Boses", settings: "Settings",
    // HOME
    good_morning: "Magandang Umaga", good_afternoon: "Magandang Tanghali",
    good_evening: "Magandang Gabi",
    quick_access: "Mabilis na Access", all_features: "Lahat ng features",
    disaster_tips: "Mga Tip sa Sakuna", tap_to_expand: "I-tap para palawakin",
    marked_safe: "Ligtas na",
    status_unknown: "Hindi Alam ang Katayuan", mark_safe: "MARKAHAN\nLIGTAS",
    safe: "LIGTAS", your_status: "IYONG KATAYUAN", student: "Estudyante",
    ctu_drrmo_system: "CTU Danao Campus - DRRMO System",
    emergency_quick_access: "Mabilis na Emergency Access",
    immediate_help: "Agarang tulong at rescue options",
    call_911: "Tumawag 911",
    emergency_active: "AKTIBONG EMERHENSYA", emergency_alert: "Alerto sa Emerhensya",
    view_evacuation_centers: "Tingnan ang Evacuation Centers",
    drrmo_announcement: "ANUNSYO NG DRRMO",
    stay_prepared: "Manatiling Handa", always_ready: "Laging handa",
    tap_to_collapse: "I-tap para isara", tap_for_quick_tip: "I-tap para sa mabilis na tip",
    flood: "Baha", earthquake: "Lindol", typhoon: "Bagyo", fire: "Sunog",
    flood_tip: "Pumunta agad sa mas mataas na lugar. Iwasang lumakad sa umaagos na tubig. Huwag magmaneho sa binahang kalsada.",
    earthquake_tip: "Dumapa, Magkubli, at Kumapit. Lumayo sa bintana at mabibigat na kasangkapan.",
    typhoon_tip: "Manatili sa loob. Lumayo sa bintana at pinto. I-unplug ang electrical appliances.",
    fire_tip: "Gamitin ang evacuation routes. Manatiling mababa para maiwasan ang usok. Huwag gumamit ng elevator.",
    go_bag: "Go Bag", family_plan: "Plano ng Pamilya", know_routes: "Alamin ang Ruta",
    go_bag_desc: "3-araw na suplay: pagkain, tubig, gamot, dokumento.",
    family_plan_desc: "Maghanda ng meeting point at listahan ng kontak.",
    first_aid_desc: "Alamin ang basic first aid at CPR.",
    know_routes_desc: "Alamin ang pinakamalapit na evacuation center.",
    online: "Online", offline: "Offline",
    // EVACUATION
    evacuation_title: "Mga Sentro ng Evacuation",
    evacuation_sub: "Mga Ligtas na Lugar sa Danao City",
    evacuation_alert: "ALERTO SA EVACUATION", emergency_mode_active: "AKTIBO ANG EMERGENCY MODE",
    state_emergency: "KALAGAYAN NG EMERHENSYA", evacuate_now: "Kalagayan ng Emerhensya - Lumikas Ngayon!",
    proceed_nearest: "Pumunta AGAD sa pinakamalapit na evacuation center sa ibaba",
    nearest: "PINAKAMALAPIT", go_here_now: "PUMUNTA DITO NGAYON",
    start_navigation: "SIMULAN ANG NAVIGATION", persons: "tao",
    primary: "Primary", secondary: "Secondary", away: "ang layo",
    calculating_safe_zone: "Kinakalkula ang pinakamalapit na ligtas na lugar...",
    location_unavailable: "Hindi Makita ang Lokasyon", allow_location: "Payagan ang lokasyon para tumpak ang resulta",
    view_all_maps: "Tingnan Lahat sa Google Maps", see_all_safe_zones: "Tingnan ang lahat ng ligtas na lugar malapit sa Danao City",
    go: "PUNTA", avoid_areas: "Iwasan ang mga Lugar na Ito", stay_away_zones: "Lumayo sa mga zone na ito sa panahon ng emerhensya",
    danger_note: "Ang mga mapanganib na lugar ay tinukoy ng lokal na DRRMO. Laging sundin ang opisyal na evacuation orders at iwasan ang mga lugar na ito sa panahon ng sakuna.",
    evacuation_tips: "Mga Tip sa Evacuation", follow_emergencies: "Sundin ito sa panahon ng emerhensya",
    safe_zones: "Ligtas na Lugar", danger_zones: "Mapanganib na Lugar",
    monitoring: "Pagmamatyag", centers: "Mga Sentro",
    danger: "Mapanganib", tips: "Mga Tip",
    ctu_drrmo_hotline: "CTU Danao DRRMO Hotline",
    // FIRST AID
    firstaid_title: "Unang Lunas",
    firstaid_sub: "Mga hakbang sa emerhensya",
    guides: "Mga Gabay", emergency: "Emerhensya", offline_label: "Libre",
    all: "Lahat", critical: "Kritikal",
    injury: "Sugat", disaster: "Sakuna",
    // FAMILY
    family_title: "Pamilya at Mga Kaibigan",
    family_sub: "Manatiling konektado sa panahon ng emerhensya",
    contacts: "Mga Kontak", requests: "Mga Kahilingan", find: "Hanapin",
    i_am_safe: "Ligtas Ako", need_help: "Kailangan Ko ng Tulong",
    // SETTINGS
    settings_title: "Mga Setting", language_label: "Wika",
    app_language_en: "Ang app ay nasa English",
    app_language_ceb: "Ang app ay nasa Cebuano",
    app_language_fil: "Ang app ay nasa Tagalog",
    appearance: "Hitsura", dark_mode: "Dark Mode",
    dark_theme_enabled: "Naka-enable ang dark theme", light_theme_enabled: "Naka-enable ang light theme",
    notifications_label: "Mga Abiso", emergency_alerts: "Mga Alerto sa Emerhensya",
    receiving_alerts: "Tumatanggap ng real-time alerts", alerts_disabled: "Naka-disable ang alerts",
    voice_speed: "Bilis ng Boses", account: "Account",
    slow: "Mabagal", normal: "Normal", fast: "Mabilis",
    edit_name: "I-edit ang Pangalan", change_password: "Baguhin ang Password",
    update_name_desc: "I-update ang pangalan mo sa app",
    update_password_desc: "I-update ang password ng account mo",
    information: "Impormasyon", about: "Tungkol sa LIFELINE",
    privacy: "Patakaran sa Privacy", logout: "Mag-logout",
    version_info: "Impormasyon sa bersyon at credits", data_handling: "Paano namin hinahawakan ang iyong data",
    active: "Aktibo", close: "Isara", display_name: "Display name",
    current_password: "Kasalukuyang password", new_password: "Bagong password",
    confirm_new_password: "Kumpirmahin ang bagong password", saving: "Sine-save...",
    // PROFILE
    profile_title: "Aking Profile",
    profile_sub: "Pamahalaan ang iyong impormasyon",
    personal_info: "Personal na Impormasyon", emergency_contact: "Kontak sa Emerhensya",
    edit_profile: "I-edit ang Profile", save_changes: "I-save ang Pagbabago",
    cancel: "Kanselahin",
    saved: "Na-save!", profile_updated: "Na-update na ang iyong profile.",
    full_name: "Buong Pangalan", email: "Email", phone_number: "Numero ng Telepono",
    barangay_address: "Barangay / Address", contact_name: "Pangalan ng Kontak",
    contact_number: "Numero ng Kontak", current_location: "Kasalukuyang Lokasyon",
    address_privacy: "Privacy ng Address", address_public: "Public ang Address",
    address_private: "Private ang Address", contacts_can_see_address: "Makikita ng iyong contacts ang address mo",
    only_you_address: "Ikaw lang ang makakakita ng address mo", your_name: "Iyong Pangalan",
    enter_name: "Ilagay ang iyong pangalan", enter_phone: "Ilagay ang numero ng telepono",
    enter_address: "Ilagay ang iyong address",
    windy_map: "Windy Map", unknown: "Hindi Kilala",
    permission_denied: "Hindi Pinayagan", location_required: "Kailangan ang access sa lokasyon.",
    could_not_fetch_weather: "Hindi makuha ang panahon. Suriin ang iyong internet connection.",
    try_again: "Subukan Muli", no_weather_data: "Walang weather data.",
    notification_sent: "Naipadala ang abiso sa iyong device", feels_like: "Pakiramdam ay",
    humidity: "Humidity", wind: "Hangin", visibility: "Visibility", pressure: "Pressure",
    next_24_hours: "Susunod na 24 Oras", sun_schedule: "Iskedyul ng Araw",
    sunrise: "Pagsikat", sunset: "Paglubog", earthquake_monitor: "Monitor ng Lindol",
    usgs_detection: "USGS Real-Time Detection",
    quake_desc: "Awtomatikong mino-monitor ng LIFELINE ang USGS earthquake data kada 15 minuto. Kung may Magnitude 4.0+ na lindol malapit sa Danao City, lahat ng users ay maaalerto agad.",
    check_now: "Suriin Ngayon", official_updates: "Opisyal na Updates",
    refresh_weather: "I-refresh ang Panahon",
    windy_info: "Live wind, rain, at typhoon map powered by Windy",
    loading_windy: "Nilo-load ang Windy Map...",
    quake_detected: "May Lindol na Nakita!",
    quake_detected_msg: "May makabuluhang lindol na nakita malapit sa Danao City. Na-activate ang emergency alert para sa LAHAT ng users.",
    no_quake_detected: "Walang Lindol na Nakita",
    no_quake_msg: "Walang makabuluhang lindol (Magnitude 4.0+) na nakita malapit sa Danao City sa nakaraang 24 oras.",
    check_quake_error: "Hindi masuri ang earthquake data. Suriin ang iyong internet connection.",
    voice_guide: "Gabay sa Boses", voice_sub: "Audio na instruksyon sa paglikas",
    select_language: "Pumili ng Wika:", how_to_use: "Paano gamitin",
    voice_how_desc: "Pumili ng uri ng sakuna sa ibaba, pagkatapos i-tap ang Start Voice Guide para marinig ang sunod-sunod na instruksyon. I-tap ang kahit anong hakbang para ulitin.",
    choose_disaster: "Pumili ng Uri ng Sakuna", voice_detail_sub: "Voice-Guided na Instruksyon sa Evacuation",
    start_voice: "Simulan ang Voice Guide", stop: "Itigil", steps_tap: "hakbang - I-tap para simulan ang voice guide",
    emergency_hotlines: "Emergency Hotlines", tap_number_call: "I-tap ang numero para direktang tumawag",
    call: "Tawag",
    my_status: "Aking Katayuan", no_pending_requests: "Walang pending na kahilingan",
    search_add_people: "Maghanap ng pamilya o kaibigan para idagdag sila.",
    contact_requests_here: "Dito lalabas ang contact requests.",
    no_users_found: "Walang users na nakita", lifeline_user: "LIFELINE User",
    added: "Naidagdag", add: "+ Add", message_placeholder: "Mag-type ng mensahe...",
    preparedness_checklists: "Mga Checklist sa Paghahanda",
    checklist_sub: "I-track ang iyong disaster readiness - awtomatikong nase-save ang progress",
    reset_checklist: "I-reset ang Checklist", completed: "natapos",
    items_completed: "items natapos", checklist_complete: "Kumpleto ang Checklist!",
    checklist_complete_sub: "Mahusay! Handa ka na.",
    overall_preparedness: "Kabuuang Paghahanda", ready: "Handa",
    total_items_completed: "total items natapos",
    disaster_guides: "Mga Gabay sa Sakuna", offline_mode: "Aktibo ang Offline Mode",
    before: "Bago", during: "Habang", after: "Pagkatapos", step: "Hakbang",
    firstaid_emergency_procedure: "PROSESO SA EMERHENSYA", steps: "Mga Hakbang",
    done: "Tapos", progress: "Progress", emergency_hotline: "Emergency Hotline",
    drrm_safe_zones: "DRRM at Ligtas na Lugar",
    drrm_sub: "Impormasyon sa Kaligtasan ng CTU Danao Campus",
    drrm_awareness: "Kaalaman sa DRRM", view_ctu_maps: "Tingnan ang CTU Danao sa Google Maps",
    see_campus_layout: "Tingnan ang campus layout at ligtas na lugar",
    ctu_safe_zones: "CTU Danao Ligtas na Lugar", hazard_zones: "Hazard Zones",
    topics_tap: "topics - I-tap para basahin",
    // GENERAL
    back: "Bumalik", search: "Maghanap sa pangalan...",
    no_contacts: "Wala pang mga kontak", find_people: "Humanap ng Tao",
    call_now: "I-tap para tumawag", tap_navigate: "I-tap para buksan sa Google Maps",
  },
};

export function SettingsProvider({ children }) {
  const [language, setLanguage] = useState("en");
  const [darkMode, setDarkMode] = useState(false);
  const [notifications, setNotifications] = useState(true);
  const [voiceSpeed, setVoiceSpeed] = useState("normal");

  useEffect(() => {
    (async () => {
      try {
        const savedLang = await AsyncStorage.getItem("language");
        const savedDark = await AsyncStorage.getItem("darkMode");
        const savedNotif = await AsyncStorage.getItem("notifications");
        const savedSpeed = await AsyncStorage.getItem("voiceSpeed");
        if (savedLang) setLanguage(savedLang);
        if (savedDark !== null) setDarkMode(savedDark === "true");
        if (savedNotif !== null) setNotifications(savedNotif === "true");
        if (savedSpeed) setVoiceSpeed(savedSpeed);
      } catch (e) {}
    })();
  }, []);

  const updateLanguage = async (val) => { setLanguage(val); await AsyncStorage.setItem("language", val); };
  const updateDarkMode = async (val) => { setDarkMode(val); await AsyncStorage.setItem("darkMode", String(val)); };
  const updateNotifications = async (val) => { setNotifications(val); await AsyncStorage.setItem("notifications", String(val)); };
  const updateVoiceSpeed = async (val) => { setVoiceSpeed(val); await AsyncStorage.setItem("voiceSpeed", String(val)); };

  // Translate function — t("key") returns the string in the current language
  const t = (key) => TRANSLATIONS[language]?.[key] ?? TRANSLATIONS["en"][key] ?? key;

  const theme = {
    bg: darkMode ? "#121212" : "#ffffff",
    surface: darkMode ? "#1e1e1e" : "#f5f5f5",
    card: darkMode ? "#2c2c2c" : "#ffffff",
    border: darkMode ? "#333333" : "#e0e0e0",
    textDark: darkMode ? "#ffffff" : "#1a1a1a",
    textMid: darkMode ? "#cccccc" : "#555555",
    textLight: darkMode ? "#999999" : "#888888",
    primary: "#B00020",
  };

  return (
    <SettingsContext.Provider value={{
      language, updateLanguage,
      darkMode, updateDarkMode,
      notifications, updateNotifications,
      voiceSpeed, updateVoiceSpeed,
      theme, t,
    }}>
      {children}
    </SettingsContext.Provider>
  );
}
